# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - '5000:5000'
#     environment:
#       DB_HOST: mysql
#       DB_PORT: 3306
#       DB_NAME: investdb
#       DB_USER: investuser
#       DB_PASSWORD: your_password_here
#       PORT: 5000
#       JWT_SECRET: YourJWTSecretKey
#       EMAIL_USER: youremail@gmail.com
#       EMAIL_PASS: your_email_password
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:latest
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: sahil
#       MYSQL_DATABASE: investdb
#       MYSQL_USER: investuser
#       MYSQL_PASSWORD: sahil
#     ports:
#       - '3307:3306'
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: gripinvest-backend
    ports:
      - '5000:5000'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: investdb
      DB_USER: investuser
      DB_PASSWORD: sahil
      PORT: 5000
      JWT_SECRET: YourJWTSecretKey
      EMAIL_USER: youremail@gmail.com
      EMAIL_PASS: your_email_password
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    command: npm start

  mysql:
    image: mysql:latest
    container_name: gripinvest-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sahil
      MYSQL_DATABASE: investdb
      MYSQL_USER: investuser
      MYSQL_PASSWORD: sahil
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: gripinvest-frontend
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_BASE_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
    command: npm start
    depends_on:
      - backend

volumes:
  mysql-data:
